### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by RitaS25** [haubna/PhysicsMod#902] opened 2024-05-27 21:29 UTC
Installed mod and crashes after installation. Exit code 
![IMG_2378](https://github.com/haubna/PhysicsMod/assets/170982601/e2a49a62-dfad-4f89-a270-be6e8121a9e5)
![IMG_2379](https://github.com/haubna/PhysicsMod/assets/170982601/7a24f1a5-af34-444a-8daf-1f0826889ee9)

**Comment by haubna** [comment] 2024-06-04 07:05
Can you upload the file instead of a screenshot? There is not enough information in the screenshot to diagnose the cause of the issue.

**Comment by haubna** [comment] 2024-06-21 13:11
Closed due to missing crash log but might be fixed with v170d.

**Closed as completed by haubna** 2024-06-21 13:11 UTC
Labels: bug
