### ISSUE TITLE
Some entity models seem to weirdly elongate when ragdolling

### ISSUE THREAD

**Issue by Gamershy** [haubna/PhysicsMod#333] opened 2022-05-01 01:44 UTC
I'm not certain how to describe this. I guess the best way to try to is to say that physics joint positions are horribly offset when some entities die, such as spiders, creepers, etc

Spawn a Creeper or Spider, and kill it while their respective physics setting is set to "ragdoll" 

No screenshot, but I recorded a video: https://youtu.be/26cQoB3C8M0

Minecraft Version: 1.18.2
Physics Mod Version: 2.6.10

It is worth noting that I did try deleting configs in case something weirdly corrupted, but to no avail. Only other mods I have installed in this instance are Create, Chisels n' Bits, Optifine, Flywheel, and Sound Physics.

**Comment by haubna** [comment] 2022-05-01 17:34
You might've a resource pack installed that uses CEM of Optifine which is not supported and never will be.

**Comment by Gamershy** [comment] 2022-05-01 18:30
I showed in my video that there were no resource packs applied, only mod resources and vanilla.

**Comment by Gamershy** [comment] 2022-05-01 18:44
Just ran a test, shaders are not the issue either.

**Comment by haubna** [comment] 2022-05-01 20:06
Resource packs can be custom entity animations as well. Please remove them and try again. If that doesn't work remove mod by mod and let me know which one causes the issue.

**Comment by haubna** [comment] 2022-05-01 20:07
But just as a side note: it is probably caused by Flywheel.

**Comment by Gamershy** [comment] 2022-05-01 20:14
That's really strange because it was never an issue before, it used to work just fine. Guess I'll have to live without mob physics. Also, mod resources cannot be removed, they're part of the modpack.
Also, no custom mobs, unless you consider what Create does as entities.

**Comment by haubna** [comment] 2022-05-01 20:14
Did you try? It was just a guess, doesn't have to be Flywheel.

**Comment by Gamershy** [comment] 2022-05-01 22:01
Getting ready to test now, sorry, wasn't able to get on til now. I'll update ya on what I find.

**Comment by Gamershy** [comment] 2022-05-01 22:16
I have tested by removing mods
Neither Create nor Flywheel are the cause (Flywheel is a required API for Create, so I removed both together)
Sound Physics is not the cause (dunno how it would've been to begin with lol)
Chisels n Bits is not the cause (Was really banking on it)
Upon removing ALL mods, the issue stopped, which made me realize something with the only mod I did not remove
I just now removed Optifine, and left all other mods. The issue stopped, which means Optifine is officially the issue.
Version the error occurs on is HD_U_H7
If you'd like, I can try using an older version (or newer if one is available) to see if the issue persists. Though this is my first time using the 1.18.2 versions.

**Comment by Gamershy** [comment] 2022-05-01 22:26
Alright, one final post, I decided to downgrade Optifine to HD_U_H6, and the issue does NOT persist, meaning some change in H7 seems to be the culprit.

**Comment by Answordy** [comment] 2022-05-02 11:43
Yeah I can confirm this, it's Optifine HD_U_H7, you can either downgrade or turn off ragdoll for these mobs, I personally set them to blocky, It looks better on creeper anyways.

**Comment by Gamershy** [comment] 2022-05-02 13:01
I set up my settings to be in line with how the mobs ragdoll/break apart in Dungeons. Plus it's more entertaining to watch creepers blast into the stratosphere after exploding, imo.

**Comment by haubna** [comment] 2022-10-11 08:39
Resource packs can be custom entity animations as well. Please remove them
and try again. If that doesn't work remove mod by mod and let me know which
one causes the issue.

Gamershy ***@***.***> schrieb am So. 1. Mai 2022 um 20:30:

**Comment by haubna** [comment] 2023-03-11 10:20
Fixed with 2.11.6

**Closed as completed by haubna** 2023-03-11 10:20 UTC
Labels: bug
