### ISSUE TITLE
Crash Rendering Error [BUG]

### ISSUE THREAD

**Issue by ChromaToggled** [haubna/PhysicsMod#382] opened 2022-06-20 13:28 UTC
The Game Crashes when you lead a mob with the physics mod on.

Start Minecraft on Fabric 1.19 (0.14.8) With sodium and iris and the physics mod pro v53, start a new world and lead any animal.

here is the crash log https://www.mediafire.com/file/ft8wmrqc9pztgi4/crash-2022-06-20_15.08.35-client.txt/file

Minecraft Version: <Fabric 1.19 0.14.8>
Physics Mod Version: <v53, 2.8.1>

**Comment by haubna** [comment] 2022-06-20 14:00
Doesn't happen with only Iris + Sodium installed. Probably another mod that causes this incompatibility. You need to test which mod causes this issue (might be pehkui or skinlayers mod).

**Comment by haubna** [comment] 2022-08-25 20:51
This issue was caused by Pehkui and is fixed now.

**Closed as completed by haubna** 2022-08-25 20:51 UTC
Labels: compatibility
