### ISSUE TITLE
Entities flickering with some shaders

### ISSUE THREAD

**Issue by slidedrum** [haubna/PhysicsMod#105] opened 2021-09-07 13:53 UTC
I am running Minecraft 1.17.1 fabric Iris shaders, when I have Physics mod installed all entities flicker rapidly sometimes.  I can replicate most often with sliders vibrant shaders.  But it does happen with others as well.  Here is a video of the issue: https://streamable.com/zddo46 I do have other mods installed in the video, however the issue persists with only fabric api, iris, and physicsmod.

**Comment by haubna** [comment] 2021-09-07 13:55
Please send me a clip with only Iris and Physics Mod installed so I can
reproduce this.

slidedrum ***@***.***> schrieb am Di. 7. Sep. 2021 um 15:53:

**Comment by haubna** [comment] 2021-09-07 14:25
And please include the versions of the mods you are using.

**Comment by slidedrum** [comment] 2021-09-07 19:28
Here is a video with only Iris, physics mod, and fabric api.  https://streamable.com/fj4x1j
And here is the mods folder once I removed everything 
![image](https://user-images.githubusercontent.com/14340641/132400213-d4911c29-43a9-468d-9cfd-9d4c71a5a355.png)

**Comment by haubna** [comment] 2021-09-07 19:29
Perfect! I will try to fix this as soon as possible :)

**Comment by haubna** [comment] 2021-09-08 06:11
Which Sildurs Shaders are you using? I couldn't reproduce it with the Lite version here: https://sildurs-shaders.github.io/

**Comment by slidedrum** [comment] 2021-09-08 16:11
> Which Sildurs Shaders are you using? I couldn't reproduce it with the Lite version here: https://sildurs-shaders.github.io/

Yes that's what I was using, but I was using the high variant in that video. I can see if it happens on my system with low. It also happened with (almost) all of the other shaders in the list from the video.

**Comment by haubna** [comment] 2021-09-08 16:22
This might be a coding bug by me which gets covered up by modern graphics card drivers. Which graphics card are you using + driver versions?

**Comment by slidedrum** [comment] 2021-09-08 16:28
> This might be a coding bug by me which gets covered up by modern graphics card drivers. Which graphics card are you using + driver versions?

I have tried updating my drivers, I am using a RTX 3090, I was using driver version 471.41.  and I am now using  471.96.  Issue persists on both.  

But I have noticed that it does not happen on 2 render distance (or at least is MUCH less common), I had it on 32.  So it may either be related to performance, or render distance.  Are you able to reproduce it at a higher render distance and or lower frame rate?  Though I was not able to reproduce the issue at 2 render distance while limiting my frame rate to 15 with in game settings.

**Comment by haubna** [comment] 2021-09-08 16:50
Huh, I tried high and low render distances + high and low framerates. Still not happening. Neither in dev environment nor in normal environment.

**Comment by slidedrum** [comment] 2021-09-08 17:43
> Huh, I tried high and low render distances + high and low framerates. Still not happening. Neither in dev environment nor in normal environment.

That is very strange.  Well I can't really expect you to fix it if you can't reproduce it.  Hopefully someone can figure something out to figure out what is going on.

**Comment by yobson1** [comment] 2021-12-02 22:08
I'm also facing this issue, it seems to only occur once I've travelled a bit from where I load in. Can be quite inconsistent, I was having the issue very frequently but when I tried again to replicate it to demonstrate I had trouble replicating it at first.

On minecraft version 1.18, physics mod version 2.5.18 basic edition, using the iris starline fork that can be found [here](https://github.com/HyperCubeMC/Iris) specifically [this build](https://github.com/HyperCubeMC/Iris/actions/runs/1501273261)

https://streamable.com/rpgcre
![mods](https://i.imgur.com/FyIF1et.png)

**Comment by haubna** [comment] 2021-12-02 22:10
Starline fork is not supported. Only the official Iris build is supported. If you can find a consistent way to reproduce it the original Iris build please let me know.

**Comment by yobson1** [comment] 2021-12-02 22:16
I hadn't tried regular Iris until now, but it looks like it has the same behaviour. https://streamable.com/kzbs30

**Comment by haubna** [comment] 2021-12-02 22:18
I need a consistent way to reproduce it. Doesn't happen on my end. Play with the settings and let me know if changing any of it helps.

**Comment by Drakkar666** [comment] 2021-12-06 14:25
Hey, just wanted to chime in and let you know that I am also having this issue in 1.18.
I made a clean Fabric version with these mods installed:
![image](https://user-images.githubusercontent.com/26894238/144860109-900aabd5-8bbe-4e71-b0ab-51a551652877.png)
And without changing any settings in both Physics and Sodium the flickering still occurs if shaders are turned on (I tried Sildurs Vibrant Shaders Lite and Complementary Shaders)
I tried playing around with async settings (like assigning more CPU threads to chunk loading etc.) but they unfortunately don't seem to affect this, I also attempted to use only 1 thread for everything in Physics, turning off Mob Physics but no luck.

I did check my logs and there seems to be an OpenGL error thrown around, but I have no idea if it's related to this issue, so apologies in advance.
`OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Target buffer must be bound.'`

Here are my specs if that helps:

- GPU: Gigabyte GeForce RTX 3070 Ti 8 GB GAMING OC

- CPU: Intel Core i7-8700K

- RAM: Corsair Vengeance RGB Pro SL 32 GB

- Motherboard: Asus Prime Z370-A

- OS: Windows 10 Home

**Comment by haubna** [comment] 2021-12-25 20:55
Could you send me the log with those OpenGL bug messages?

**Comment by Drakkar666** [comment] 2021-12-25 21:42
I... I can't reproduce it anymore. I re-downloaded mods above with the same version, and used the same Fabric client (1.18, 0.12.8) with the same JVM arguments. 

There was a Windows update and Nvidia drivers update between my comment and this reproduction attempt, so this could be the reason why. 

I also deleted the logs related to this issue, I'm sorry. :(

**Comment by haubna** [comment] 2021-12-25 23:03
I've found the issue. Should be fixed in version 2.6.1

**Closed as completed by haubna** 2021-12-25 23:03 UTC
Labels: bug
