### ISSUE TITLE
Fishing Rod not reeling in

### ISSUE THREAD

**Issue by sirvko** [haubna/PhysicsMod#187] opened 2021-11-08 16:30 UTC
Fishing rod's line does not reel in when using First Person mod.

When using first person mod and use the fishing rod and try to reel in, the line does not reel in.

![image](https://user-images.githubusercontent.com/92441901/140780492-e7ad2117-3494-48ae-ae18-69a90aa655be.png)

Minecraft Version: 1.17.1
Physics Mod Version: 2.5.15

**Comment by sirvko** [comment] 2021-11-08 16:31
oops i forgot to make the tag compatability

**Comment by haubna** [comment] 2021-12-10 20:36
Probably caused by the PvP compatibility setting. Turn it to off. Fixed in version 2.5.18.

**Closed as completed by haubna** 2021-12-10 20:36 UTC
Labels: bug
