### ISSUE TITLE
Crash Shortly After World Loads

### ISSUE THREAD

**Issue by S-moreo** [haubna/PhysicsMod#521] opened 2023-01-12 04:36 UTC
World loads, then immediately crashes.

Minecraft Version: 1.19.2
Physics Mod Version: pro-v106

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-01-11 23:27:18
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_3218 cannot be cast to class net.minecraft.class_638 (net.minecraft.class_3218 and net.minecraft.class_638 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @80ec1f8)
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
	at net.diebuddies.physics.snow.SnowWorld.applyEntitySnowTracks(SnowWorld.java:273)
	at net.diebuddies.physics.snow.SnowWorld.update(SnowWorld.java:96)
	at net.diebuddies.physics.PhysicsWorld.update(PhysicsWorld.java:168)
	at net.minecraft.client.render.GameRenderer.handler$efh000$render(GameRenderer:5658)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.diebuddies.physics.snow.SnowWorld.applyEntitySnowTracks(SnowWorld.java:273)
	at net.diebuddies.physics.snow.SnowWorld.update(SnowWorld.java:96)
	at net.diebuddies.physics.PhysicsWorld.update(PhysicsWorld.java:168)
	at net.minecraft.class_757.handler$efh000$render(class_757.java:5658)

-- Affected level --
Details:
	All players: 1 total; [class_746['_Smoreo'/70, l='ClientLevel', x=121.02, y=111.00, z=-968.08]]
	Chunk stats: 1024, 669
	Level dimension: minecraft:overworld
	Level spawn location: World: (-55,69,-726), Section: (at 9,5,10 in -4,4,-46; chunk contains blocks -64,-64,-736 to -49,319,-721), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Level time: 2282273 game time, 3008365 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, minecraft/physicsmod, Snowyspirit Generated Pack, Supplementaries Generated Pack

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2744314616 bytes (2617 MiB) / 6945767424 bytes (6624 MiB) up to 8556380160 bytes (8160 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.05
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2756
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 34727.18
	Virtual memory used (MB): 24552.20
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx8156M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.1.0
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.4.62
		badpackets: Bad Packets 0.2.1
		bclib: BCLib 2.1.5
		betteradvancements: Better Advancements 0.3.0.148
		betteranimationscollection: Better Animations Collection 4.0.5
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstats: Better Statistics Screen 2.1.1+1.19.2
			tcdcommons: TCD Commons API 1.1+1.19.2
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterthirdperson: Better Third Person 1.9.0
		bettertridents: Better Tridents 4.0.1
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
		bookshelf: Bookshelf 16.2.16
		carryon: Carry On 2.0.2.3
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chat_heads: Chat Heads 0.9.0
		chiselsandbits: chisels-and-bits 1.3.123
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			saeculariacaudices: Saecularia Caudices 1.0.14
			scena: Scena 1.0.89
		cleancut: CleanCut 1.19.2-5.1-fabric
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		comforts: Comforts 6.0.3+1.19.2
		continuity: Continuity 2.0.1+1.19
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			noindium: No Indium? 1.1.0+1.19
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		ctov: ChoiceTheorem's Overhauled Villages 3.1.4
		decorative_blocks: Decorative Blocks 3.0.0
		diagonalfences: Diagonal Fences 4.2.3
		dynmus: Dynamic Music 2.2.1+1.19.2
		enchanted-vertical-slabs: Enchanted Vertical Slabs 1.6
		fabric-api: Fabric API 0.71.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.14+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.10+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.31+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.5+2d2baf4b90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.33+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.3+9785ec3590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.5+9785ec3590
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+08b73de490
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.4+4d0d570390
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		forgeconfigapiport: Forge Config API Port 4.2.10
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendsandfoes: Friends&Foes 1.6.6
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		go-fish: Go Fish 1.6.0-1.19.1
		illuminations: Illuminations 1.10.11
		indium: Indium 1.0.9+mc1.19.2
		inventoryprofilesnext: Inventory Profiles Next 1.9.1
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.5.0.297
		jeresources: Just Enough Resources 1.2.1.189
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 2.0.1
		lithium: Lithium 0.10.4
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.2
		moonlight: Moonlight 1.19.2-2.1.26
		mousewheelie: Mouse Wheelie 1.10.6+mc1.19.2
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.19+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.7.1+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc22w17a
		notenoughanimations: NotEnoughAnimations 1.6.2
		notenoughcrashes: Not Enough Crashes 4.2.1+1.19.2
		observable: Observable 3.3.1
		paxi: Paxi 1.19.2-Fabric-3.0.1
		physicsmod: Physics Mod 2.9.5
		pickupnotifier: Pick Up Notifier 4.2.0
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		satin: Satin 1.9.0
		snowyspirit: Snowy Spirit 1.19.2-2.1.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		strawgolem: Straw Golem 2.0.0-beta.5
		supplementaries: Supplementaries 1.19.2-2.2.35
		tipsmod: Tips 8.0.27
		tradingpost: Trading Post 4.2.0
		twilightforest: The Twilight Forest 4.2.333
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.642+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.642+1.19.2
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.642+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.642+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.642+1.19.2
				porting_lib_models: Porting Lib Models 2.1.642+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.642+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.642+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.642+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.642+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.642+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.642+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.642+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.642+1.19.2
						porting_lib_common: Porting Lib Common 2.1.642+1.19.2
		veinmining: Vein Mining 1.0.2+1.19.2
			spectrelib: SpectreLib 0.11.0+1.19
		visuality: Visuality 0.5.5
		visualworkbench: Visual Workbench 4.2.1
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		zoomify: Zoomify 2.9.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.5
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.5
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.5
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.5
	Loaded Shaderpack: (off)
	NEC status: Has NEC: INVALID
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 527.56, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, minecraft/physicsmod, Snowyspirit Generated Pack, Supplementaries Generated Pack
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['_Smoreo'/70, l='ServerLevel[Just the Two of Us]', x=121.02, y=111.00, z=-968.08]]
	Data Packs: vanilla, Fabric Mods, Snowyspirit Generated Pack, Supplementaries Generated Pack
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Physics Mod (physicsmod), Minecraft (minecraft), Fabric Loader (fabricloader)

**Comment by haubna** [comment] 2023-01-12 11:12
I just uploaded v107. The crash hasn't been fixed but I would need another crash-report + latest.log with the new version to identify the cause. Thanks in advance!

**Comment by S-moreo** [comment] 2023-01-13 00:54
Updated to v107, same issue. Hope this helps!

[crash-2023-01-12_19.51.50-client.txt](https://github.com/haubna/PhysicsMod/files
[latest.log](https://github.com/haubna/PhysicsMod/files/10407198/latest.log)
/10407197/crash-2023-01-12_19.51.50-client.txt)

**Comment by S-moreo** [comment] 2023-01-13 00:55
[crash-2023-01-12_19.51.50-client.txt](https://github.com/haubna/PhysicsMod/files/10407201/crash-2023-01-12_19.51.50-client.txt)

**Comment by haubna** [comment] 2023-01-13 01:00
Perfect, I should be able to fix it now, thanks!

**Comment by haubna** [comment] 2023-01-14 12:00
Fixed in v108

**Closed as completed by haubna** 2023-01-14 12:00 UTC
Labels: bug
