### ISSUE TITLE
all entity-objects+items flicker with iris [BUG]

### ISSUE THREAD

**Issue by wackiestwow** [haubna/PhysicsMod#220] opened 2021-12-17 01:57 UTC
**Describe the bug**
entities, items and mobs flicker when using sodium+optifine. not using physics with iris and sodium causes no issues.

**To Reproduce**
1: put sodium+optifine and physics mod into mods folder

2: run fabric 1.18.1

3: enter a world, and flickering begins in seconds

**Screenshots**
player:
![2021-12-16_15 46 38](https://user-images.githubusercontent.com/95980287/146476563-dedd0a9a-5dca-403b-b040-aa373802e64d.png)
mobs:
![2021-12-16_15 59 18](https://user-images.githubusercontent.com/95980287/146476580-5d197e2a-c2de-4e0f-a0aa-e476273c0efe.png)
chests:
![2021-12-16_15 59 41](https://user-images.githubusercontent.com/95980287/146476604-d66354b7-4d03-448e-a0dd-f20c21c485ef.png)

Minecraft Version: 1.18.1
Physics Mod Version: 2.5.18

**Comment by haubna** [comment] 2021-12-21 21:45
Some other users have experienced this too. I can't reproduce this issue. Do you use the default settings on Sodium or do you have anything changed? Does this happen without Iris + Sodium?

**Comment by haubna** [comment] 2021-12-25 20:55
Which graphics card do you have? Could you check the Minecraft log if it contains any OpenGL bug messages?

**Comment by haubna** [comment] 2021-12-25 23:04
I've found the issue. Should be fixed in 2.6.1.

**Closed as completed by haubna** 2021-12-25 23:04 UTC
Labels: bug
