### ISSUE TITLE
PhysicsMod crashes game when joining server

### ISSUE THREAD

**Issue by Chris6ix** [haubna/PhysicsMod#884] opened 2024-05-09 16:21 UTC
**Describe the bug**
I use PhysicsMod in a custom modpack, and it crashes sometimes when I join my server
There is no normal error log generated, but a Java Runtime Error is. As I don't understand much about it, I had someone look at it, and they said that it's PhysicsMod not liking my AMD GPU.
Here is the error log: https://pastes.dev/jD9kQymlR6

**To Reproduce**
Join Server using PhysicsMod and an AMD GPU?

**Screenshots**
/

Minecraft Version: 1.20.1
Physics Mod Version: pro-v167d-forge-1.20.1

**Comment by haubna** [comment] 2024-05-20 08:45
Try disabling smoke or "Use No Error Context" in the Performance menu of Sodium (if installed). Could you let me know if that works for you?

**Comment by Chris6ix** [comment] 2024-05-29 15:55
Hey, sorry for the late response, I haven't played MC in the last week. I just tried it with `Use No Error Context` disabled, and it still crashes. Smoke was always disabled. Here is the new error log in case it helps: 
[hs_err_pid19388.log](https://github.com/haubna/PhysicsMod/files/15487068/hs_err_pid19388.log)

**Comment by haubna** [comment] 2024-06-21 13:11
I was able to find the cause and it is fixed with v170d. Thanks for the report!

**Closed as completed by haubna** 2024-06-21 13:11 UTC
Labels: bug

**Comment by Chris6ix** [comment] 2024-06-21 17:46
Great! Thank you :)
